//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_conversation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub key_id: Option<i32>,
    pub model: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_api_key::Entity",
        from = "Column::KeyId",
        to = "super::ai_api_key::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AiApiKey,
    #[sea_orm(has_many = "super::ai_message::Entity")]
    AiMessage,
}

impl Related<super::ai_api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiApiKey.def()
    }
}

impl Related<super::ai_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
