//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub conversation_id: i32,
    pub role: String,
    pub content: String,
    pub created_at: String,
    pub input_tokens: Option<i32>,
    pub output_tokens: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_conversation::Entity",
        from = "Column::ConversationId",
        to = "super::ai_conversation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AiConversation,
    #[sea_orm(has_many = "super::ai_valuation_proposal::Entity")]
    AiValuationProposal,
}

impl Related<super::ai_conversation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiConversation.def()
    }
}

impl Related<super::ai_valuation_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiValuationProposal.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
