//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_valuation_proposal")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub message_id: i32,
    pub model: String,
    #[sea_orm(column_type = "Text")]
    pub payload: String,
    #[sea_orm(column_type = "Text")]
    pub preview: String,
    pub status: String,
    pub created_valuation_id: Option<i32>,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ai_message::Entity",
        from = "Column::MessageId",
        to = "super::ai_message::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AiMessage,
    #[sea_orm(
        belongs_to = "super::valuation::Entity",
        from = "Column::CreatedValuationId",
        to = "super::valuation::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Valuation,
}

impl Related<super::ai_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AiMessage.def()
    }
}

impl Related<super::valuation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Valuation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
