//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub alert_rule_id: i32,
    pub is_triggered: bool,
    pub message: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::alert_rule::Entity",
        from = "Column::AlertRuleId",
        to = "super::alert_rule::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AlertRule,
}

impl Related<super::alert_rule::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AlertRule.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
