//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "alert_rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub target_type: String,
    pub valuation_id: Option<i32>,
    pub condition: String,
    pub coin: Option<String>,
    pub indicator: Option<String>,
    pub is_active: bool,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::valuation::Entity",
        from = "Column::ValuationId",
        to = "super::valuation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Valuation,
}

impl Related<super::valuation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Valuation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
