//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "banks_inputs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub valuation_id: i32,
    #[sea_orm(column_type = "Double")]
    pub book_value_per_share: f64,
    #[sea_orm(column_type = "Double")]
    pub roe: f64,
    #[sea_orm(column_type = "Double")]
    pub payout: f64,
    #[sea_orm(column_type = "Double")]
    pub ke: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::valuation::Entity",
        from = "Column::ValuationId",
        to = "super::valuation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Valuation,
}

impl Related<super::valuation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Valuation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
