//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "crypto_indicators")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub coin: String,
    pub indicator: String,
    pub reading_date: String,
    #[sea_orm(column_type = "Double")]
    pub raw_value: f64,
    pub signal: String,
    pub source: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
