//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "dcf_inputs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub valuation_id: i32,
    #[sea_orm(column_type = "Double")]
    pub ebit: f64,
    #[sea_orm(column_type = "Double")]
    pub tax_rate: f64,
    #[sea_orm(column_type = "Double")]
    pub depreciation_amortization: f64,
    #[sea_orm(column_type = "Double")]
    pub capex: f64,
    #[sea_orm(column_type = "Double")]
    pub nwc_change: f64,
    #[sea_orm(column_type = "Double")]
    pub total_debt: f64,
    #[sea_orm(column_type = "Double")]
    pub cash: f64,
    #[sea_orm(column_type = "Double")]
    pub shares_outstanding: f64,
    #[sea_orm(column_type = "Double")]
    pub beta: f64,
    #[sea_orm(column_type = "Double")]
    pub risk_free_rate: f64,
    #[sea_orm(column_type = "Double")]
    pub market_risk_premium: f64,
    #[sea_orm(column_type = "Double")]
    pub kd: f64,
    #[sea_orm(column_type = "Double")]
    pub perpetuity_growth: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::valuation::Entity",
        from = "Column::ValuationId",
        to = "super::valuation::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Valuation,
}

impl Related<super::valuation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Valuation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
