//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod ai_api_key;
pub mod ai_conversation;
pub mod ai_message;
pub mod ai_valuation_proposal;
pub mod alert_event;
pub mod alert_rule;
pub mod banks_inputs;
pub mod bazin_inputs;
pub mod crypto_indicators;
pub mod dcf_inputs;
pub mod gordon_inputs;
pub mod graham_inputs;
pub mod indicator_thresholds;
pub mod projected_ceiling_inputs;
pub mod rim_inputs;
pub mod rnav_inputs;
pub mod stock_dcf_fundamentals;
pub mod stock_dividend_payments;
pub mod stock_dividends_avg;
pub mod stock_fundamentals;
pub mod stock_notes;
pub mod stock_quotes;
pub mod stock_technicals;
pub mod valuation;
