//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_technicals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub sma_50: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sma_100: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sma_200: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cagr_5y: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cagr_10y: Option<f64>,
    pub source: String,
    pub fetched_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
