//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_dividend_payments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub payment_date: String,
    #[sea_orm(column_type = "Double")]
    pub amount: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub price_at_payment: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub yield_pct: Option<f64>,
    pub source: String,
    pub fetched_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
