//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "stock_dcf_fundamentals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub reference_year: i32,
    #[sea_orm(column_type = "Double")]
    pub ebit: f64,
    #[sea_orm(column_type = "Double", nullable)]
    pub depreciation_amortization: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub capex: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub nwc_change: f64,
    #[sea_orm(column_type = "Double")]
    pub total_debt: f64,
    #[sea_orm(column_type = "Double")]
    pub cash: f64,
    #[sea_orm(column_type = "Double")]
    pub shares_outstanding: f64,
    pub source: String,
    pub fetched_at: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub tax_rate: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
