//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "valuation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ticker: String,
    pub reference_year: i32,
    #[sea_orm(column_type = "Double")]
    pub current_price: f64,
    pub model: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub fair_price: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub safety_margin: Option<f64>,
    pub verdict: Option<String>,
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::banks_inputs::Entity")]
    BanksInputs,
    #[sea_orm(has_many = "super::bazin_inputs::Entity")]
    BazinInputs,
    #[sea_orm(has_many = "super::dcf_inputs::Entity")]
    DcfInputs,
    #[sea_orm(has_many = "super::gordon_inputs::Entity")]
    GordonInputs,
    #[sea_orm(has_many = "super::graham_inputs::Entity")]
    GrahamInputs,
    #[sea_orm(has_many = "super::rnav_inputs::Entity")]
    RnavInputs,
}

impl Related<super::banks_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BanksInputs.def()
    }
}

impl Related<super::bazin_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BazinInputs.def()
    }
}

impl Related<super::dcf_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DcfInputs.def()
    }
}

impl Related<super::gordon_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GordonInputs.def()
    }
}

impl Related<super::graham_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GrahamInputs.def()
    }
}

impl Related<super::rnav_inputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RnavInputs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
